export { default as Footer } from "./Footer";
export { default as Register } from "./Register";
export { default as Header } from "./Header";
export { default as Login } from "./Login";
export { default as Products } from "./Products";
export { default as Details } from "./Details";
export { default as Admin } from "./Admin";
export { default as AdminCreate } from "./AdminCreate";
export { default as MyCart } from "./MyCart";
